version: "3.9"

services:
  std:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=:0
      - DISABLE_ROS1_EOL_WARNINGS=1
    volumes:
      - type: bind
        source: ~/.ros/log
        target: /root/.ros/log
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
      - type: bind
        source: ~/catkin_src2
        target: /root/catkin_ws/src
      - type: bind
        source: ~/ros_src2
        target: /root/src
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyACM0:/dev/ttyACM0
