version: "3.9"

services:
  phoxi:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISPLAY=:0
    volumes:
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    stdin_open: true
    tty: true
    network_mode: host
    depends_on:
      - rosnoetic
    devices:
      - /dev/dri:/dev/dri
    command:
      - bash -c "PhoXiControl"
  rosnoetic:
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      - DISPLAY=:0
    working_dir: /root
    volumes:
      - type: bind
        source: ~/catkin_ws/src
        target: /root/catkin_ws/src
      - type: bind
        source: ~/src
        target: /root/src
      - type: bind
        source: ~/.ros/log
        target: /root/.ros/log
      - type: bind
        source: /tmp/.X11-unix
        target: /tmp/.X11-unix
    stdin_open: true
    tty: true
    network_mode: host
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0
    #   - /dev/ttyACM0:/dev/ttyACM0